program mathTest;
var a, b, c, d : integer;


begin
	writeln('This is test 1 of C Level');
	writeln('Output should be as indicated');
	writeln('');

	a := 10;
	b := 5;
	c := 100;
	d := 30;

	writeln('a is ', a);
	writeln('b is ', b);
	writeln('c is ', c);
	writeln('d is ', d);

	writeln('');
	writeln('a + b = ', a + b);
	writeln('b - c = ', b - c);
	writeln('c * d = ', c * d);
	writeln('d div a = ', d div a);



end.

