program mathTest;
var a, b, c, d : float;


begin
	writeln('This is test 3 of C Level');
	writeln('Output should be as indicated');
	writeln('');

	a := 10.0;
	b := 5;
	c := 100;
	d := 12.3456;

	writeln('a is ', a);
	writeln('b is ', b);
	writeln('c is ', c);
	writeln('d is ', d);

	writeln('');
	writeln('a + b = ', a + b);
	writeln('b - c = ', b - c);
	writeln('c * d = ', c * d);
	writeln('d / a = ', d / a);


end.

